"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import TYPE_CHECKING
from importlib import import_module
import builtins
import sys

if TYPE_CHECKING:
    from .canvasrequesttype import CanvasRequestType
    from .controlnet_input import (
        ControlnetInput,
        ControlnetInputTypedDict,
        InitImageType,
        StrengthType,
    )
    from .controlnet_type import ControlnetType
    from .custom_model_type import CustomModelType
    from .element_input import ElementInput, ElementInputTypedDict
    from .job_status import JobStatus
    from .lcm_generation_style import LcmGenerationStyle
    from .model_asset_texture_types import ModelAssetTextureTypes
    from .motion_resolution import MotionResolution
    from .motion_variation_type import MotionVariationType
    from .pricingcalculatorservices import PricingCalculatorServices
    from .sd_generation_schedulers import SdGenerationSchedulers
    from .sd_generation_style import SdGenerationStyle
    from .sd_versions import SdVersions
    from .security import Security, SecurityTypedDict
    from .strength import Strength
    from .universal_upscaler_style import UniversalUpscalerStyle
    from .universal_upscaler_ultra_style import UniversalUpscalerUltraStyle
    from .user_elements_input import UserElementsInput, UserElementsInputTypedDict
    from .variation_type import VariationType

__all__ = [
    "CanvasRequestType",
    "ControlnetInput",
    "ControlnetInputTypedDict",
    "ControlnetType",
    "CustomModelType",
    "ElementInput",
    "ElementInputTypedDict",
    "InitImageType",
    "JobStatus",
    "LcmGenerationStyle",
    "ModelAssetTextureTypes",
    "MotionResolution",
    "MotionVariationType",
    "PricingCalculatorServices",
    "SdGenerationSchedulers",
    "SdGenerationStyle",
    "SdVersions",
    "Security",
    "SecurityTypedDict",
    "Strength",
    "StrengthType",
    "UniversalUpscalerStyle",
    "UniversalUpscalerUltraStyle",
    "UserElementsInput",
    "UserElementsInputTypedDict",
    "VariationType",
]

_dynamic_imports: dict[str, str] = {
    "CanvasRequestType": ".canvasrequesttype",
    "ControlnetInput": ".controlnet_input",
    "ControlnetInputTypedDict": ".controlnet_input",
    "InitImageType": ".controlnet_input",
    "StrengthType": ".controlnet_input",
    "ControlnetType": ".controlnet_type",
    "CustomModelType": ".custom_model_type",
    "ElementInput": ".element_input",
    "ElementInputTypedDict": ".element_input",
    "JobStatus": ".job_status",
    "LcmGenerationStyle": ".lcm_generation_style",
    "ModelAssetTextureTypes": ".model_asset_texture_types",
    "MotionResolution": ".motion_resolution",
    "MotionVariationType": ".motion_variation_type",
    "PricingCalculatorServices": ".pricingcalculatorservices",
    "SdGenerationSchedulers": ".sd_generation_schedulers",
    "SdGenerationStyle": ".sd_generation_style",
    "SdVersions": ".sd_versions",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "Strength": ".strength",
    "UniversalUpscalerStyle": ".universal_upscaler_style",
    "UniversalUpscalerUltraStyle": ".universal_upscaler_ultra_style",
    "UserElementsInput": ".user_elements_input",
    "UserElementsInputTypedDict": ".user_elements_input",
    "VariationType": ".variation_type",
}


def dynamic_import(modname, retries=3):
    for attempt in range(retries):
        try:
            return import_module(modname, __package__)
        except KeyError:
            # Clear any half-initialized module and retry
            sys.modules.pop(modname, None)
            if attempt == retries - 1:
                break
    raise KeyError(f"Failed to import module '{modname}' after {retries} attempts")


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = dynamic_import(module_name)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = builtins.list(_dynamic_imports.keys())
    return builtins.sorted(lazy_attrs)
