"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from leonardo_ai_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, NotRequired, TypedDict


class UserElementsInputTypedDict(TypedDict):
    user_lora_id: NotRequired[Nullable[float]]
    r"""Unique identifier for user custom element."""
    weight: NotRequired[Nullable[float]]
    r"""Weight for the element"""


class UserElementsInput(BaseModel):
    user_lora_id: Annotated[
        OptionalNullable[float], pydantic.Field(alias="userLoraId")
    ] = UNSET
    r"""Unique identifier for user custom element."""

    weight: OptionalNullable[float] = UNSET
    r"""Weight for the element"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["userLoraId", "weight"])
        nullable_fields = set(["userLoraId", "weight"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    UserElementsInput.model_rebuild()
except NameError:
    pass
