workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://api-docs-nine-delta.vercel.app/cloud/openapi.json
        registry:
            location: registry.speakeasyapi.dev/leonardo-ai/leonardo-ai/my-source
targets:
    leonardo-python-sdk:
        target: python
        source: my-source
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/leonardo-ai/leonardo-ai/my-source-python-code-samples
