"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
import httpx
from leonardo_ai_sdk.models.shared import (
    cost as shared_cost,
    element_input as shared_element_input,
)
from leonardo_ai_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateTextToVideoGenerationString(str, Enum):
    r"""The model to use for the video generation. Defaults to MOTION2 if not specified."""

    MOTION2 = "MOTION2"
    VEO3 = "VEO3"
    MOTION2_FAST = "MOTION2FAST"
    VEO3_FAST = "VEO3FAST"
    KLING2_1 = "KLING2_1"
    KLING2_5 = "KLING2_5"


class CreateTextToVideoGenerationMotionString(str, Enum):
    r"""The resolution of the output video. Acceptable values vary based on model"""

    RESOLUTION_480 = "RESOLUTION_480"
    RESOLUTION_720 = "RESOLUTION_720"
    RESOLUTION_1080 = "RESOLUTION_1080"


class CreateTextToVideoGenerationRequestBodyTypedDict(TypedDict):
    r"""Query parameters can also be provided in the request body as a JSON object"""

    prompt: str
    r"""The prompt used to generate video"""
    duration: NotRequired[Nullable[int]]
    r"""Duration of the output video in seconds. Defaults to 8 seconds if not specified. Allowed values: 4, 6, or 8. Supported on models VEO3 and VEO3FAST."""
    elements: NotRequired[Nullable[List[shared_element_input.ElementInputTypedDict]]]
    r"""An array of elements/loras objects that will be applied sequentially to the output. Elements are only supported for Motion2.0 generations."""
    frame_interpolation: NotRequired[Nullable[bool]]
    r"""Smoothly blend frames for fluid video transitions using Interpolation."""
    height: NotRequired[Nullable[int]]
    r"""Height of the output video. Acceptable values vary based on model"""
    is_public: NotRequired[Nullable[bool]]
    r"""Whether the generation is public or not"""
    model: NotRequired[Nullable[CreateTextToVideoGenerationString]]
    r"""The model to use for the video generation. Defaults to MOTION2 if not specified."""
    negative_prompt: NotRequired[Nullable[str]]
    r"""The negative prompt used for the video generation."""
    prompt_enhance: NotRequired[Nullable[bool]]
    r"""Whether to enhance the prompt."""
    prompt_enhance_instruction: NotRequired[Nullable[str]]
    r"""A natural language instruction used to modify the main prompt. For example, 'make it cinematic', 'add a rainbow', or 'change the subject to a cat'."""
    resolution: NotRequired[Nullable[CreateTextToVideoGenerationMotionString]]
    r"""The resolution of the output video. Acceptable values vary based on model"""
    seed: NotRequired[Nullable[int]]
    r"""Apply a fixed seed to maintain consistency across generation sets. The maximum seed value is 2147483637 for Motion 2.0 and 4294967293 for Veo3."""
    style_ids: NotRequired[Nullable[List[str]]]
    r"""Predefined styles to enhance the prompt. This accepts a list of style uuids."""
    width: NotRequired[Nullable[int]]
    r"""Width of the output video. Acceptable values vary based on model"""


class CreateTextToVideoGenerationRequestBody(BaseModel):
    r"""Query parameters can also be provided in the request body as a JSON object"""

    prompt: str
    r"""The prompt used to generate video"""

    duration: OptionalNullable[int] = 8
    r"""Duration of the output video in seconds. Defaults to 8 seconds if not specified. Allowed values: 4, 6, or 8. Supported on models VEO3 and VEO3FAST."""

    elements: OptionalNullable[List[shared_element_input.ElementInput]] = UNSET
    r"""An array of elements/loras objects that will be applied sequentially to the output. Elements are only supported for Motion2.0 generations."""

    frame_interpolation: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="frameInterpolation")
    ] = UNSET
    r"""Smoothly blend frames for fluid video transitions using Interpolation."""

    height: OptionalNullable[int] = UNSET
    r"""Height of the output video. Acceptable values vary based on model"""

    is_public: Annotated[OptionalNullable[bool], pydantic.Field(alias="isPublic")] = (
        UNSET
    )
    r"""Whether the generation is public or not"""

    model: OptionalNullable[CreateTextToVideoGenerationString] = (
        CreateTextToVideoGenerationString.MOTION2
    )
    r"""The model to use for the video generation. Defaults to MOTION2 if not specified."""

    negative_prompt: Annotated[
        OptionalNullable[str], pydantic.Field(alias="negativePrompt")
    ] = UNSET
    r"""The negative prompt used for the video generation."""

    prompt_enhance: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="promptEnhance")
    ] = UNSET
    r"""Whether to enhance the prompt."""

    prompt_enhance_instruction: Annotated[
        OptionalNullable[str], pydantic.Field(alias="promptEnhanceInstruction")
    ] = UNSET
    r"""A natural language instruction used to modify the main prompt. For example, 'make it cinematic', 'add a rainbow', or 'change the subject to a cat'."""

    resolution: OptionalNullable[CreateTextToVideoGenerationMotionString] = UNSET
    r"""The resolution of the output video. Acceptable values vary based on model"""

    seed: OptionalNullable[int] = UNSET
    r"""Apply a fixed seed to maintain consistency across generation sets. The maximum seed value is 2147483637 for Motion 2.0 and 4294967293 for Veo3."""

    style_ids: Annotated[
        OptionalNullable[List[str]], pydantic.Field(alias="styleIds")
    ] = UNSET
    r"""Predefined styles to enhance the prompt. This accepts a list of style uuids."""

    width: OptionalNullable[int] = UNSET
    r"""Width of the output video. Acceptable values vary based on model"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "duration",
                "elements",
                "frameInterpolation",
                "height",
                "isPublic",
                "model",
                "negativePrompt",
                "promptEnhance",
                "promptEnhanceInstruction",
                "resolution",
                "seed",
                "styleIds",
                "width",
            ]
        )
        nullable_fields = set(
            [
                "duration",
                "elements",
                "frameInterpolation",
                "height",
                "isPublic",
                "model",
                "negativePrompt",
                "promptEnhance",
                "promptEnhanceInstruction",
                "resolution",
                "seed",
                "styleIds",
                "width",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class CreateTextToVideoGenerationMotionVideoGenerationOutputTypedDict(TypedDict):
    api_credit_cost: NotRequired[Nullable[int]]
    r"""API credits cost, available for Production API users. Note: it will be deprecated. Please use the cost instead."""
    cost: NotRequired[Nullable[shared_cost.CostTypedDict]]
    r"""The cost of the operation."""
    generation_id: NotRequired[str]


class CreateTextToVideoGenerationMotionVideoGenerationOutput(BaseModel):
    api_credit_cost: Annotated[
        OptionalNullable[int],
        pydantic.Field(
            deprecated="warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible.",
            alias="apiCreditCost",
        ),
    ] = UNSET
    r"""API credits cost, available for Production API users. Note: it will be deprecated. Please use the cost instead."""

    cost: OptionalNullable[shared_cost.Cost] = UNSET
    r"""The cost of the operation."""

    generation_id: Annotated[Optional[str], pydantic.Field(alias="generationId")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["apiCreditCost", "cost", "generationId"])
        nullable_fields = set(["apiCreditCost", "cost"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class CreateTextToVideoGenerationResponseBodyTypedDict(TypedDict):
    r"""Responses for POST /generations-text-to-video"""

    motion_video_generation_job: NotRequired[
        Nullable[CreateTextToVideoGenerationMotionVideoGenerationOutputTypedDict]
    ]


class CreateTextToVideoGenerationResponseBody(BaseModel):
    r"""Responses for POST /generations-text-to-video"""

    motion_video_generation_job: Annotated[
        OptionalNullable[CreateTextToVideoGenerationMotionVideoGenerationOutput],
        pydantic.Field(alias="motionVideoGenerationJob"),
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["motionVideoGenerationJob"])
        nullable_fields = set(["motionVideoGenerationJob"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class CreateTextToVideoGenerationResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    object: NotRequired[CreateTextToVideoGenerationResponseBodyTypedDict]
    r"""Responses for POST /generations-text-to-video"""


class CreateTextToVideoGenerationResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    object: Optional[CreateTextToVideoGenerationResponseBody] = None
    r"""Responses for POST /generations-text-to-video"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["object"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CreateTextToVideoGenerationRequestBody.model_rebuild()
except NameError:
    pass
try:
    CreateTextToVideoGenerationMotionVideoGenerationOutput.model_rebuild()
except NameError:
    pass
try:
    CreateTextToVideoGenerationResponseBody.model_rebuild()
except NameError:
    pass
