"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
import httpx
from leonardo_ai_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateVideoUpscaleString(str, Enum):
    r"""The resolution of the upscaled video. RESOLUTION_720 is the only option for now."""

    RESOLUTION_720 = "RESOLUTION_720"


class CreateVideoUpscaleRequestBodyTypedDict(TypedDict):
    r"""Query parameters can also be provided in the request body as a JSON object"""

    resolution: CreateVideoUpscaleString
    r"""The resolution of the upscaled video. RESOLUTION_720 is the only option for now."""
    source_generation_id: str
    r"""The ID of the source video generation to upscale."""


class CreateVideoUpscaleRequestBody(BaseModel):
    r"""Query parameters can also be provided in the request body as a JSON object"""

    resolution: CreateVideoUpscaleString
    r"""The resolution of the upscaled video. RESOLUTION_720 is the only option for now."""

    source_generation_id: Annotated[str, pydantic.Field(alias="sourceGenerationId")]
    r"""The ID of the source video generation to upscale."""


class CreateVideoUpscaleMotionVideoGenerationOutputTypedDict(TypedDict):
    api_credit_cost: NotRequired[Nullable[int]]
    r"""API credits cost, available for Production API users."""
    generation_id: NotRequired[str]
    variation_id: NotRequired[str]
    r"""The ID of the upscale variation."""


class CreateVideoUpscaleMotionVideoGenerationOutput(BaseModel):
    api_credit_cost: Annotated[
        OptionalNullable[int], pydantic.Field(alias="apiCreditCost")
    ] = UNSET
    r"""API credits cost, available for Production API users."""

    generation_id: Annotated[Optional[str], pydantic.Field(alias="generationId")] = None

    variation_id: Annotated[Optional[str], pydantic.Field(alias="variationId")] = None
    r"""The ID of the upscale variation."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["apiCreditCost", "generationId", "variationId"]
        nullable_fields = ["apiCreditCost"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


class CreateVideoUpscaleResponseBodyTypedDict(TypedDict):
    r"""Responses for POST /generations-text-to-video"""

    motion_video_generation_job: NotRequired[
        Nullable[CreateVideoUpscaleMotionVideoGenerationOutputTypedDict]
    ]


class CreateVideoUpscaleResponseBody(BaseModel):
    r"""Responses for POST /generations-text-to-video"""

    motion_video_generation_job: Annotated[
        OptionalNullable[CreateVideoUpscaleMotionVideoGenerationOutput],
        pydantic.Field(alias="motionVideoGenerationJob"),
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["motionVideoGenerationJob"]
        nullable_fields = ["motionVideoGenerationJob"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


class CreateVideoUpscaleResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    object: NotRequired[CreateVideoUpscaleResponseBodyTypedDict]
    r"""Responses for POST /generations-text-to-video"""


class CreateVideoUpscaleResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    object: Optional[CreateVideoUpscaleResponseBody] = None
    r"""Responses for POST /generations-text-to-video"""
