"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from leonardo_ai_sdk.models.shared import (
    apierror as shared_apierror,
    nodeinput as shared_nodeinput,
)
from leonardo_ai_sdk.types import BaseModel, Nullable, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class InputTypedDict(TypedDict):
    node_inputs: List[shared_nodeinput.NodeInputTypedDict]
    r"""Array of node input objects to customize the Blueprint"""
    public: bool
    r"""Whether the resulting generations should be public"""
    collection_ids: NotRequired[List[Nullable[int]]]
    r"""Optional list of collection IDs to add the generations to"""


class Input(BaseModel):
    node_inputs: Annotated[
        List[shared_nodeinput.NodeInput], pydantic.Field(alias="nodeInputs")
    ]
    r"""Array of node input objects to customize the Blueprint"""

    public: bool
    r"""Whether the resulting generations should be public"""

    collection_ids: Annotated[
        Optional[List[Nullable[int]]], pydantic.Field(alias="collectionIds")
    ] = None
    r"""Optional list of collection IDs to add the generations to"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["collectionIds"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ExecuteBlueprintRequestBodyTypedDict(TypedDict):
    blueprint_version_id: str
    r"""The unique identifier of the Blueprint Version to execute"""
    input: InputTypedDict


class ExecuteBlueprintRequestBody(BaseModel):
    blueprint_version_id: Annotated[str, pydantic.Field(alias="blueprintVersionId")]
    r"""The unique identifier of the Blueprint Version to execute"""

    input: Input


class ExecuteBlueprintTypedDict(TypedDict):
    ak_uuid: str
    r"""The unique identifier of the Blueprint Execution"""


class ExecuteBlueprint(BaseModel):
    ak_uuid: Annotated[str, pydantic.Field(alias="akUUID")]
    r"""The unique identifier of the Blueprint Execution"""


class SuccessResponseTypedDict(TypedDict):
    execute_blueprint: ExecuteBlueprintTypedDict


class SuccessResponse(BaseModel):
    execute_blueprint: Annotated[
        ExecuteBlueprint, pydantic.Field(alias="executeBlueprint")
    ]


ExecuteBlueprintResponseBodyTypedDict = TypeAliasType(
    "ExecuteBlueprintResponseBodyTypedDict",
    Union[SuccessResponseTypedDict, List[shared_apierror.APIErrorTypedDict]],
)
r"""Responses for POST /blueprint-executions"""


ExecuteBlueprintResponseBody = TypeAliasType(
    "ExecuteBlueprintResponseBody",
    Union[SuccessResponse, List[shared_apierror.APIError]],
)
r"""Responses for POST /blueprint-executions"""


class ExecuteBlueprintResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    one_of: NotRequired[ExecuteBlueprintResponseBodyTypedDict]
    r"""Responses for POST /blueprint-executions"""


class ExecuteBlueprintResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    one_of: Optional[ExecuteBlueprintResponseBody] = None
    r"""Responses for POST /blueprint-executions"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["oneOf"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Input.model_rebuild()
except NameError:
    pass
try:
    ExecuteBlueprintRequestBody.model_rebuild()
except NameError:
    pass
try:
    ExecuteBlueprint.model_rebuild()
except NameError:
    pass
try:
    SuccessResponse.model_rebuild()
except NameError:
    pass
