"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
import httpx
from leonardo_ai_sdk.models.shared import (
    apierror as shared_apierror,
    blueprint as shared_blueprint,
    pageinfo as shared_pageinfo,
)
from leonardo_ai_sdk.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class Platforms(str, Enum):
    ANDROID = "Android"
    I_OS = "iOS"
    WEB = "Web"
    API = "API"


class ListBlueprintsRequestBodyTypedDict(TypedDict):
    after: NotRequired[str]
    r"""Cursor to paginate forward from"""
    before: NotRequired[str]
    r"""Cursor to paginate backward from"""
    categories: NotRequired[List[str]]
    r"""Filter Blueprints by category"""
    first: NotRequired[int]
    r"""Number of items to return after the cursor (forward pagination)"""
    last: NotRequired[int]
    r"""Number of items to return before the cursor (backward pagination)"""
    platforms: NotRequired[List[Platforms]]
    r"""Filter Blueprints by platforms that they can be executed on"""


class ListBlueprintsRequestBody(BaseModel):
    after: Optional[str] = None
    r"""Cursor to paginate forward from"""

    before: Optional[str] = None
    r"""Cursor to paginate backward from"""

    categories: Optional[List[str]] = None
    r"""Filter Blueprints by category"""

    first: Optional[int] = 10
    r"""Number of items to return after the cursor (forward pagination)"""

    last: Optional[int] = None
    r"""Number of items to return before the cursor (backward pagination)"""

    platforms: Optional[List[Platforms]] = None
    r"""Filter Blueprints by platforms that they can be executed on"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["after", "before", "categories", "first", "last", "platforms"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class EdgesTypedDict(TypedDict):
    cursor: NotRequired[str]
    r"""An opaque cursor used for pagination"""
    node: NotRequired[shared_blueprint.BlueprintTypedDict]
    r"""A Blueprint object"""


class Edges(BaseModel):
    cursor: Optional[str] = None
    r"""An opaque cursor used for pagination"""

    node: Optional[shared_blueprint.Blueprint] = None
    r"""A Blueprint object"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["cursor", "node"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class BlueprintsTypedDict(TypedDict):
    edges: NotRequired[List[EdgesTypedDict]]
    page_info: NotRequired[shared_pageinfo.PageInfoTypedDict]
    r"""Pagination information following the Relay cursor pagination spec"""
    total_count: NotRequired[int]
    r"""Total number of results available"""


class Blueprints(BaseModel):
    edges: Optional[List[Edges]] = None

    page_info: Annotated[
        Optional[shared_pageinfo.PageInfo], pydantic.Field(alias="pageInfo")
    ] = None
    r"""Pagination information following the Relay cursor pagination spec"""

    total_count: Annotated[Optional[int], pydantic.Field(alias="totalCount")] = None
    r"""Total number of results available"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["edges", "pageInfo", "totalCount"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class OneTypedDict(TypedDict):
    r"""Successful response with Blueprint data"""

    blueprints: BlueprintsTypedDict


class One(BaseModel):
    r"""Successful response with Blueprint data"""

    blueprints: Blueprints


ListBlueprintsResponseBodyTypedDict = TypeAliasType(
    "ListBlueprintsResponseBodyTypedDict",
    Union[OneTypedDict, List[shared_apierror.APIErrorTypedDict]],
)
r"""Responses for GET /api/rest/v1/blueprints"""


ListBlueprintsResponseBody = TypeAliasType(
    "ListBlueprintsResponseBody", Union[One, List[shared_apierror.APIError]]
)
r"""Responses for GET /api/rest/v1/blueprints"""


class ListBlueprintsResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    one_of: NotRequired[ListBlueprintsResponseBodyTypedDict]
    r"""Responses for GET /api/rest/v1/blueprints"""


class ListBlueprintsResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    one_of: Optional[ListBlueprintsResponseBody] = None
    r"""Responses for GET /api/rest/v1/blueprints"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["oneOf"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Blueprints.model_rebuild()
except NameError:
    pass
