"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from leonardo_ai_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UploadCanvasInitImageRequestBodyTypedDict(TypedDict):
    r"""Query parameters provided in the request body as a JSON object"""

    init_extension: str
    r"""Has to be png, jpg, jpeg, or webp."""
    mask_extension: str
    r"""Has to be png, jpg, jpeg, or webp."""


class UploadCanvasInitImageRequestBody(BaseModel):
    r"""Query parameters provided in the request body as a JSON object"""

    init_extension: Annotated[str, pydantic.Field(alias="initExtension")]
    r"""Has to be png, jpg, jpeg, or webp."""

    mask_extension: Annotated[str, pydantic.Field(alias="maskExtension")]
    r"""Has to be png, jpg, jpeg, or webp."""


class CanvasInitImageUploadOutputTypedDict(TypedDict):
    init_fields: NotRequired[Nullable[str]]
    init_image_id: NotRequired[Nullable[str]]
    init_key: NotRequired[Nullable[str]]
    init_url: NotRequired[Nullable[str]]
    mask_fields: NotRequired[Nullable[str]]
    mask_image_id: NotRequired[Nullable[str]]
    mask_key: NotRequired[Nullable[str]]
    mask_url: NotRequired[Nullable[str]]


class CanvasInitImageUploadOutput(BaseModel):
    init_fields: Annotated[
        OptionalNullable[str], pydantic.Field(alias="initFields")
    ] = UNSET

    init_image_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="initImageId")
    ] = UNSET

    init_key: Annotated[OptionalNullable[str], pydantic.Field(alias="initKey")] = UNSET

    init_url: Annotated[OptionalNullable[str], pydantic.Field(alias="initUrl")] = UNSET

    mask_fields: Annotated[
        OptionalNullable[str], pydantic.Field(alias="maskFields")
    ] = UNSET

    mask_image_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="maskImageId")
    ] = UNSET

    mask_key: Annotated[OptionalNullable[str], pydantic.Field(alias="maskKey")] = UNSET

    mask_url: Annotated[OptionalNullable[str], pydantic.Field(alias="maskUrl")] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "initFields",
                "initImageId",
                "initKey",
                "initUrl",
                "maskFields",
                "maskImageId",
                "maskKey",
                "maskUrl",
            ]
        )
        nullable_fields = set(
            [
                "initFields",
                "initImageId",
                "initKey",
                "initUrl",
                "maskFields",
                "maskImageId",
                "maskKey",
                "maskUrl",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UploadCanvasInitImageResponseBodyTypedDict(TypedDict):
    r"""Responses for POST /canvas-init-image"""

    upload_canvas_init_image: NotRequired[
        Nullable[CanvasInitImageUploadOutputTypedDict]
    ]


class UploadCanvasInitImageResponseBody(BaseModel):
    r"""Responses for POST /canvas-init-image"""

    upload_canvas_init_image: Annotated[
        OptionalNullable[CanvasInitImageUploadOutput],
        pydantic.Field(alias="uploadCanvasInitImage"),
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["uploadCanvasInitImage"])
        nullable_fields = set(["uploadCanvasInitImage"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UploadCanvasInitImageResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    object: NotRequired[UploadCanvasInitImageResponseBodyTypedDict]
    r"""Responses for POST /canvas-init-image"""


class UploadCanvasInitImageResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    object: Optional[UploadCanvasInitImageResponseBody] = None
    r"""Responses for POST /canvas-init-image"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["object"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
