"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from dataclasses_json import Undefined, dataclass_json
from leonardoaisdk import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class PromptRandomPromptGenerationOutput:
    api_credit_cost: Optional[int] = dataclasses.field(default=4, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('apiCreditCost'), 'exclude': lambda f: f is None }})
    r"""API Credits Cost for Random Prompt Generation. Available for Production API Users."""
    prompt: Optional[str] = dataclasses.field(default='The random prompt generated.', metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('prompt'), 'exclude': lambda f: f is None }})
    r"""The random prompt generated."""
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class PromptRandomResponseBody:
    r"""Responses for POST /prompt/random"""
    prompt_generation: Optional[PromptRandomPromptGenerationOutput] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('promptGeneration'), 'exclude': lambda f: f is None }})
    



@dataclasses.dataclass
class PromptRandomResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    object: Optional[PromptRandomResponseBody] = dataclasses.field(default=None)
    r"""Responses for POST /prompt/random"""
    

